version: '3.4'

services:
  battleshipnode:
    image: battleshipnode
    build:
      context: .
      dockerfile: ./DockerfileDebug
      args:
        PORT: 8080
        ADDRESS: "0.0.0.0"
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
      - "9229:9229"
